name: Linux Release

on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build
        run: |
          sudo apt install build-essential cmake
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/server
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}